server:
  port: 9993
  ip: localhost

spring:
  application:
    name: eureka

#\u6CE8\u518C\u4E2D\u5FC3\u914D\u7F6E
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #\u5C5E\u6027\u8868\u793A\u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230Eureka Server\uFF0C\u9ED8\u8BA4\u4E3Atrue
    fetch-registry: false #\u8868\u793A\u662F\u5426\u4ECEEureka Server\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u4E3Atrue\u3002 \u5982\u679C\u8FD9\u662F\u4E00\u4E2A\u5355\u70B9\u7684 Eureka Server\uFF0C\u4E0D\u9700\u8981\u540C\u6B65\u5176\u4ED6\u8282\u70B9\u7684\u6570\u636E\uFF0C\u53EF\u4EE5\u8BBE\u4E3Afalse
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
