server:
  port: 8082

spring:
  application:
    name: eureka-client-two #\u6CE8\u518C\u5728eureka\u4E2D\u7684\u670D\u52A1\u540D\u79F0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:h2:mem:dbc2m
    username: sa
    password: sa
    #schema: classpath:db/schema.sql
    #data: classpath:db/data.sql
    platform: h2

  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9993/eureka/

feign:
  hystrix:
    enabled: true #fallback\u751F\u6548
