server:
  port: 9090
  servlet:
    context-path: /

spring:
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.2.92:3306/test_shiro?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

#mybatis:
#  mapper-locations: classpath*:mapper/**/*.xml

#logging:
#  config: classpath:config/logback-spring.xml